'use client';

import { useState, useMemo, useCallback } from 'react';
import { getToolBySlug } from '@/lib/tools';
import ToolLayout from '@/components/ToolLayout';

export default function PrivacyPolicyGenerator() {
  const tool = getToolBySlug('privacy-policy-generator');
  const [siteName, setSiteName] = useState('Your Website');
  const [siteUrl, setSiteUrl] = useState('https://example.com');
  const [contactEmail, setContactEmail] = useState('privacy@example.com');
  const [effectiveDate, setEffectiveDate] = useState(new Date().toISOString().split('T')[0]);
  const [collectsEmail, setCollectsEmail] = useState(true);
  const [collectsName, setCollectsName] = useState(true);
  const [usesCookies, setUsesCookies] = useState(true);
  const [usesAnalytics, setUsesAnalytics] = useState(true);
  const [usesAds, setUsesAds] = useState(false);
  const [sellsData, setSellsData] = useState(false);
  const [copied, setCopied] = useState(false);

  const policy = useMemo(() => {
    const dataCollected: string[] = [];
    if (collectsEmail) dataCollected.push('email address');
    if (collectsName) dataCollected.push('name');
    if (usesCookies) dataCollected.push('cookies and usage data');

    return `Privacy Policy for ${siteName}

Effective Date: ${effectiveDate}

1. INTRODUCTION

Welcome to ${siteName} ("we," "our," or "us"). This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website ${siteUrl}.

Please read this privacy policy carefully. By using the Site, you agree to the collection and use of information in accordance with this policy.

2. INFORMATION WE COLLECT

${dataCollected.length > 0 ? `We may collect the following types of information:
${dataCollected.map(d => `• ${d.charAt(0).toUpperCase() + d.slice(1)}`).join('\n')}` : 'We do not collect personal information.'}

${usesCookies ? `3. COOKIES AND TRACKING TECHNOLOGIES

We use cookies and similar tracking technologies to track activity on our Site. Cookies are files with a small amount of data that are stored on your device. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent.` : ''}

${usesAnalytics ? `4. ANALYTICS

We may use third-party analytics services (such as Google Analytics) to collect, monitor, and analyze usage of our Site. These services may collect information about your use of our Site, including your IP address, browser type, pages visited, and time spent on pages.` : ''}

${usesAds ? `5. ADVERTISING

We may use third-party advertising companies to serve ads when you visit our Site. These companies may use information about your visits to provide advertisements about goods and services of interest to you.` : ''}

6. HOW WE USE YOUR INFORMATION

We may use the information we collect to:
• Provide and maintain our Site
• Notify you about changes to our Site
• Respond to your inquiries and support needs
• Monitor usage of our Site
• Detect and prevent technical issues

7. DATA SHARING

${sellsData ? 'We may share or sell your personal information to third parties for marketing purposes.' : 'We do not sell, trade, or rent your personal identification information to others.'}

We may share your information with:
• Service providers who assist in operating our Site
• Law enforcement when required by law
• Business partners with your consent

8. DATA SECURITY

We implement appropriate security measures to protect your personal information. However, no method of transmission over the Internet is 100% secure, and we cannot guarantee absolute security.

9. YOUR RIGHTS

You have the right to:
• Access your personal data
• Correct inaccurate data
• Request deletion of your data
• Object to data processing
• Data portability

10. CHILDREN'S PRIVACY

Our Site is not intended for children under 13. We do not knowingly collect personal information from children under 13.

11. CHANGES TO THIS POLICY

We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Effective Date."

12. CONTACT US

If you have questions about this Privacy Policy, please contact us at:
Email: ${contactEmail}
Website: ${siteUrl}

---
Generated by GoFreeTool.com`;
  }, [siteName, siteUrl, contactEmail, effectiveDate, collectsEmail, collectsName, usesCookies, usesAnalytics, usesAds, sellsData]);

  const copyPolicy = useCallback(async () => {
    await navigator.clipboard.writeText(policy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [policy]);

  const downloadPolicy = useCallback(() => {
    const blob = new Blob([policy], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'privacy-policy.txt';
    a.click();
    URL.revokeObjectURL(url);
  }, [policy]);

  if (!tool) return <div>Tool not found</div>;

  return (
    <ToolLayout tool={tool}>
      <section className="mb-8">
        <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
          Generate a <strong>privacy policy</strong> for your website or app. Customize for your
          data collection practices and download or copy the policy.
          <strong> All processing happens locally</strong> — your information is not stored.
        </p>
      </section>

      <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-6 mb-8">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Editor */}
          <div className="space-y-4">
            <h3 className="font-medium text-gray-900 dark:text-white">Your Information</h3>

            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Website/App Name</label>
              <input
                type="text"
                value={siteName}
                onChange={(e) => setSiteName(e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-900 text-gray-900 dark:text-white"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Website URL</label>
              <input
                type="url"
                value={siteUrl}
                onChange={(e) => setSiteUrl(e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-900 text-gray-900 dark:text-white"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Contact Email</label>
              <input
                type="email"
                value={contactEmail}
                onChange={(e) => setContactEmail(e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-900 text-gray-900 dark:text-white"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Effective Date</label>
              <input
                type="date"
                value={effectiveDate}
                onChange={(e) => setEffectiveDate(e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-900 text-gray-900 dark:text-white"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Data Collection</label>
              <div className="space-y-2">
                {[
                  { label: 'Email addresses', checked: collectsEmail, onChange: setCollectsEmail },
                  { label: 'Names', checked: collectsName, onChange: setCollectsName },
                  { label: 'Cookies', checked: usesCookies, onChange: setUsesCookies },
                  { label: 'Analytics (Google Analytics, etc.)', checked: usesAnalytics, onChange: setUsesAnalytics },
                  { label: 'Advertising/Third-party ads', checked: usesAds, onChange: setUsesAds },
                  { label: 'We sell/share data with third parties', checked: sellsData, onChange: setSellsData },
                ].map((item, i) => (
                  <label key={i} className="flex items-center gap-2">
                    <input
                      type="checkbox"
                      checked={item.checked}
                      onChange={(e) => item.onChange(e.target.checked)}
                      className="rounded text-teal-600 focus:ring-teal-500"
                    />
                    <span className="text-sm text-gray-700 dark:text-gray-300">{item.label}</span>
                  </label>
                ))}
              </div>
            </div>
          </div>

          {/* Preview */}
          <div>
            <div className="flex items-center justify-between mb-4">
              <h3 className="font-medium text-gray-900 dark:text-white">Preview</h3>
              <div className="flex gap-2">
                <button
                  onClick={copyPolicy}
                  className="px-3 py-1 text-sm bg-teal-600 hover:bg-teal-700 text-white rounded transition-colors"
                >
                  {copied ? 'Copied!' : 'Copy'}
                </button>
                <button
                  onClick={downloadPolicy}
                  className="px-3 py-1 text-sm bg-gray-200 dark:bg-gray-700 hover:bg-gray-300 dark:hover:bg-gray-600 rounded transition-colors"
                >
                  Download
                </button>
              </div>
            </div>
            <div className="h-[500px] p-4 bg-gray-50 dark:bg-gray-900 rounded-lg overflow-y-auto">
              <pre className="text-sm text-gray-700 dark:text-gray-300 whitespace-pre-wrap font-sans">
                {policy}
              </pre>
            </div>
          </div>
        </div>
      </div>

      <div className="mb-12 p-4 bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 rounded-lg">
        <h3 className="font-semibold text-amber-800 dark:text-amber-300 mb-2">Disclaimer</h3>
        <p className="text-sm text-amber-700 dark:text-amber-400">
          This is a template for informational purposes only and does not constitute legal advice.
          For complete legal compliance, especially for GDPR, CCPA, or industry-specific requirements,
          consult with a qualified legal professional.
        </p>
      </div>
    </ToolLayout>
  );
}
